### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by andriawan** [CeddyG/query-builder-repository#6]
Could you please add method last (in querying last record on a table). if first method is satisfied, it think it will be possible to get last record.

**Comment by CeddyG** [comment]
Hello.

Added.

**Comment by andriawan** [comment]
Thanks. Would you mind allowing me contribute to this repo? Repository pattern with query builder is such more efficient...

**Comment by CeddyG** [comment]
Of course. I haven't a lot of time to evolve my repositories and an external help would be welcome.

And thanks for the star ;)
